"""Minimal internal event capability."""

from .models import DomainEvent, event_from_operation, new_event
from .reading import (
    ATTENTION_NAME_SUFFIXES,
    ATTENTION_STATUSES,
    EventLogDayActivity,
    EventLogSummary,
    build_event_log_summary,
    event_to_dict,
    filter_attention_events,
    filter_events,
    filter_events_by_source,
    filter_events_by_status,
    filter_events_by_workflow,
    filter_events_since,
    filter_events_until,
    is_attention_event,
    read_event_log,
    resolve_since_datetime,
    resolve_until_datetime,
    summarize_attention_event_log,
    summarize_event_activity_days,
    summarize_event_log,
    tail_attention_event_log,
    tail_event_log,
)
from .sinks import (
    CollectingEventSink,
    EventSink,
    JsonlFileEventSink,
    NoOpEventSink,
    publish_event,
    publish_events,
)

__all__ = [
    "CollectingEventSink",
    "DomainEvent",
    "ATTENTION_NAME_SUFFIXES",
    "ATTENTION_STATUSES",
    "EventLogDayActivity",
    "EventLogSummary",
    "EventSink",
    "JsonlFileEventSink",
    "NoOpEventSink",
    "build_event_log_summary",
    "event_to_dict",
    "event_from_operation",
    "filter_attention_events",
    "filter_events",
    "filter_events_by_source",
    "filter_events_by_status",
    "filter_events_by_workflow",
    "filter_events_since",
    "filter_events_until",
    "is_attention_event",
    "new_event",
    "read_event_log",
    "resolve_since_datetime",
    "resolve_until_datetime",
    "summarize_attention_event_log",
    "summarize_event_activity_days",
    "summarize_event_log",
    "tail_attention_event_log",
    "tail_event_log",
    "publish_event",
    "publish_events",
]
