"""CLI adapter layer."""

from .app import create_cli_app
from .automation import present_event_log_alert_delivery_command
from .commands import register_cli_commands
from .commands_core import register_core_commands
from .commands_notes import register_note_and_knowledge_commands
from .commands_personal import register_personal_commands
from .conversation import run_handle_input_command, run_route_input_command
from .conversation import present_handle_input_command, present_route_input_command
from .errors import exit_with_brain_ops_error
from .knowledge import (
    present_audit_vault_command,
    present_normalize_frontmatter_command,
    present_process_inbox_command,
    present_weekly_review_command,
    run_audit_vault_command,
    run_normalize_frontmatter_command,
    run_process_inbox_command,
    run_weekly_review_command,
)
from .messages import capture_result_lines, improve_result_lines, research_result_lines
from .monitoring import (
    build_event_log_alert_check_table,
    build_event_log_alert_message_table,
    build_event_log_alert_presets_table,
    build_event_log_failures_table,
    build_event_log_hotspots_table,
    build_event_log_summary_table,
    build_event_log_tail_table,
    present_event_log_alert_check_command,
    present_event_log_alert_message_command,
    present_event_log_alert_presets_command,
    present_event_log_alerts_command,
    present_event_log_failures_command,
    present_event_log_hotspots_command,
    present_event_log_report_command,
    present_event_log_summary_command,
    present_event_log_tail_command,
)
from .notes import (
    coerce_note_workflow_error,
    present_apply_link_suggestions_command,
    present_capture_command,
    present_create_note_command,
    present_create_project_command,
    present_daily_summary_command,
    present_enrich_note_command,
    present_improve_note_command,
    present_link_suggestions_command,
    present_promote_note_command,
    present_research_note_command,
    run_apply_link_suggestions_command,
    run_capture_command,
    run_create_note_command,
    run_create_project_command,
    run_daily_summary_command,
    run_enrich_note_command,
    run_improve_note_command,
    run_link_suggestions_command,
    run_promote_note_command,
    run_research_note_command,
)
from .openclaw import present_openclaw_manifest
from .personal_management import (
    present_create_diet_plan_command,
    present_set_active_diet_command,
    present_set_budget_target_command,
    present_set_habit_target_command,
    present_set_macro_targets_command,
    present_update_diet_meal_command,
    run_create_diet_plan_command,
    run_set_active_diet_command,
    run_set_budget_target_command,
    run_set_habit_target_command,
    run_set_macro_targets_command,
    run_update_diet_meal_command,
)
from .personal_logging import (
    present_daily_log_command,
    present_habit_checkin_command,
    present_log_body_metrics_command,
    present_log_expense_command,
    present_log_meal_command,
    present_log_supplement_command,
    present_log_workout_command,
    run_daily_log_command,
    run_habit_checkin_command,
    run_log_body_metrics_command,
    run_log_expense_command,
    run_log_meal_command,
    run_log_supplement_command,
    run_log_workout_command,
)
from .personal import (
    present_active_diet_command,
    present_body_metrics_status_command,
    present_budget_status_command,
    present_daily_habits_command,
    present_daily_macros_command,
    present_daily_status_command,
    present_diet_status_command,
    present_habit_status_command,
    present_macro_status_command,
    present_spending_summary_command,
    present_workout_status_command,
    run_active_diet_command,
    run_body_metrics_status_command,
    run_budget_status_command,
    run_daily_habits_command,
    run_daily_macros_command,
    run_daily_status_command,
    run_diet_status_command,
    run_habit_status_command,
    run_macro_status_command,
    run_spending_summary_command,
    run_workout_status_command,
)
from .presenters import (
    print_handle_input_result,
    print_lines_with_single_operation,
    print_json_or_rendered,
    print_json_or_rendered_with_operations,
    print_optional_json_or_rendered,
    print_operations,
    print_rendered_with_operations,
    print_rendered_with_single_operation,
)
from .json_output import print_model_json, print_optional_model_json
from .runtime import load_alert_output_dir, load_database_path, load_event_log_path, load_event_sink, load_runtime_config, load_validated_vault
from .setup import initialize_cli_config
from .system import present_info_command, present_init_command, present_init_db_command
from .tables import build_info_table, build_operations_table

__all__ = [
    "build_info_table",
    "build_event_log_alert_check_table",
    "build_event_log_alert_message_table",
    "build_event_log_alert_presets_table",
    "build_event_log_failures_table",
    "build_event_log_hotspots_table",
    "build_event_log_summary_table",
    "build_event_log_tail_table",
    "build_operations_table",
    "capture_result_lines",
    "coerce_note_workflow_error",
    "create_cli_app",
    "exit_with_brain_ops_error",
    "improve_result_lines",
    "register_cli_commands",
    "present_event_log_alert_delivery_command",
    "present_apply_link_suggestions_command",
    "present_audit_vault_command",
    "present_capture_command",
    "present_active_diet_command",
    "present_body_metrics_status_command",
    "present_budget_status_command",
    "present_create_diet_plan_command",
    "present_create_note_command",
    "present_create_project_command",
    "present_daily_habits_command",
    "present_daily_log_command",
    "present_daily_macros_command",
    "present_daily_summary_command",
    "present_daily_status_command",
    "present_diet_status_command",
    "present_enrich_note_command",
    "present_event_log_alert_check_command",
    "present_event_log_alert_message_command",
    "present_event_log_alert_presets_command",
    "present_event_log_alerts_command",
    "present_event_log_failures_command",
    "present_event_log_hotspots_command",
    "present_event_log_report_command",
    "present_event_log_tail_command",
    "present_event_log_summary_command",
    "present_handle_input_command",
    "present_habit_checkin_command",
    "present_habit_status_command",
    "present_info_command",
    "present_init_command",
    "present_init_db_command",
    "present_improve_note_command",
    "present_link_suggestions_command",
    "present_log_body_metrics_command",
    "present_log_expense_command",
    "present_log_meal_command",
    "present_log_supplement_command",
    "present_log_workout_command",
    "present_macro_status_command",
    "present_normalize_frontmatter_command",
    "present_process_inbox_command",
    "present_promote_note_command",
    "present_research_note_command",
    "present_route_input_command",
    "present_set_active_diet_command",
    "present_set_budget_target_command",
    "present_set_habit_target_command",
    "present_set_macro_targets_command",
    "present_spending_summary_command",
    "present_update_diet_meal_command",
    "present_weekly_review_command",
    "present_workout_status_command",
    "run_apply_link_suggestions_command",
    "run_active_diet_command",
    "run_handle_input_command",
    "run_audit_vault_command",
    "run_body_metrics_status_command",
    "run_budget_status_command",
    "run_capture_command",
    "run_create_diet_plan_command",
    "run_create_note_command",
    "run_create_project_command",
    "run_daily_habits_command",
    "run_daily_log_command",
    "run_daily_macros_command",
    "run_daily_summary_command",
    "run_daily_status_command",
    "run_diet_status_command",
    "run_enrich_note_command",
    "run_habit_checkin_command",
    "run_habit_status_command",
    "run_improve_note_command",
    "run_link_suggestions_command",
    "run_log_body_metrics_command",
    "run_log_expense_command",
    "run_log_meal_command",
    "run_log_supplement_command",
    "run_log_workout_command",
    "run_macro_status_command",
    "run_normalize_frontmatter_command",
    "run_promote_note_command",
    "run_process_inbox_command",
    "run_research_note_command",
    "run_route_input_command",
    "run_set_active_diet_command",
    "run_set_budget_target_command",
    "run_set_habit_target_command",
    "run_set_macro_targets_command",
    "run_spending_summary_command",
    "run_update_diet_meal_command",
    "run_weekly_review_command",
    "run_workout_status_command",
    "register_core_commands",
    "register_note_and_knowledge_commands",
    "register_personal_commands",
    "initialize_cli_config",
    "present_openclaw_manifest",
    "print_handle_input_result",
    "research_result_lines",
    "print_lines_with_single_operation",
    "print_json_or_rendered",
    "print_json_or_rendered_with_operations",
    "print_optional_json_or_rendered",
    "print_operations",
    "print_rendered_with_operations",
    "print_rendered_with_single_operation",
    "load_database_path",
    "load_alert_output_dir",
    "load_event_log_path",
    "load_event_sink",
    "load_runtime_config",
    "load_validated_vault",
    "print_model_json",
    "print_optional_model_json",
]
